### GET 
GET http://localhost:3000/api/users HTTP/1.1
set-cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJyYXJuLmpvaG5zb25AZXhhbXBsZS5jb20iLCJpYXQiOjE3Mjg1MTczNzgsImV4cCI6MTcyODUyMDk3OH0.qGEEjvulJZX4ZMZdLaYYHivjRrA_kZ5BFq9yFZsVI1k; Path=/

### GETBY
GET http://localhost:3000/api/users/66ecc4a3c20f44ee16e8fa40 HTTP/1.1
### POST
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
  "name": "sss asd",
  "email": "asd.dadad@example.com",
  "password": "555",
  "role": "user"
}
### PUT 
PUT http://localhost:3000/api/users/:id HTTP/1.1
content-type: application/json

{
  "name": "Brandon Quintero",
  "email": "asd.johnson@example.com",
  "password": "21654132",
  "role": "user"
}
### deleted
DELETE http://localhost:3000/api/users/66ef3ff6a55c35a35f79085d HTTP/1.1
content-type: application/json

{
  "name": "Brandon Quintero",
  "email": "brarn.johnson@example.com",
  "password": "21654132",
  "role": "user"
}

